# Generated by Django 5.2 on 2025-05-14 10:30

import django.db.models.deletion # type: ignore
from django.conf import settings # type: ignore
from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_customuser_is_otp_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
